# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.1.0

RUN kibana-plugin install x-pack

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
