# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0

RUN elasticsearch-plugin install license
RUN elasticsearch-plugin install shield

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
